dist: trusty
sudo: required

language: python
python:
  - "2.7"

install: "pip install nose pylint"

script: "nosetests && pylint"

addons:
  sonarcloud:
    organization: "onosadmin-github"
    token:
      secure: "ec465e74a08a67a35c595974543260b1c7911229"

jdk:
  - oraclejdk8
script:
  cd /tmp && wget https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.0.3.778-linux.zip && unzip sonar-scanner-cli-3.0.3.778-linux.zip && cd sonar-scanner-3.0.3.778-linux && sudo sudo cp -R * / && cd /tmp && git clone https://github.com/onosAdmin/onos.git && cd onos && sudo sonar-scanner     -Dsonar.projectKey=onos-sonarcloud     -Dsonar.sources=.     -Dsonar.host.url=https://sonarcloud.io      -Dsonar.organization=onosadmin-github     -Dsonar.login=ec465e74a08a67a35c595974543260b1c7911229
cache:
  directories:
    - '$HOME/.sonar/cache'

notifications:
  email:
    on_success: always # default: never
    on_failure: always # default: always
