dist: trusty
sudo: required

language: python
python:
  - "2.7"

install: "pip install nose pylint"

script: "nosetests && pylint"

addons:
  sonarcloud:
    organization: onosadmin-github
    token:
      secure: ec465e74a08a67a35c595974543260b1c7911229
jdk:
  - oraclejdk8
script:
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
