dist: trusty
sudo: required

language: python
python:
  - "2.7"

install: "pip install nose pylint"

script: "nosetests && pylint"


jdk:
  - oraclejdk8
script:
  cd /tmp && wget https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.0.3.778-linux.zip && unzip -d sonar-scanner-cli-3.0.3.778-linux.zip && cd sonar-scanner-3.0.3.778-linux && sudo sudo cp -R * / 

cache:
  directories:
    - '$HOME/.sonar/cache'
